### ISSUE TITLE
Type DSL is missing

### ISSUE THREAD

**Issue by aha-oretama** [presidenten/wdio-video-reporter#13]
**Describe the bug**
webdriverio can load config file as typescript. (see https://webdriver.io/docs/typescript.html)
But wdio-video-reporter has no type DSL, so we cannot import like this in a typescript file.

```
import * as video from 'wdio-video-reporter';
```

**To Reproduce**
See https://webdriver.io/docs/typescript.html#typed-configuration.

**Expected behavior**
 'wdio-video-reporter' can be used in typescript files.

**Environment (please complete the following information):**
 - **wdio-video-reporter version: 1.4.3
 - **WebdriverIO version:5.10.1
- **Typescript: 5.17.0
 - **Node.js version: v10.11.0
 - **NPM version: 6.9.0

**Comment by presidenten** [comment]
Whats the actual use case for this?

This library dont have any methods that are supposed to be accessed by users. It only triggers on wdio hooks and is only used in the wdio config file.

Also the import statement doesnt give any advantages over the require statement, since everything in the library is needed and thus nothing can be shaved away in treeshaking.

**Comment by aha-oretama** [comment]
I understood following meaning and I close this issue. Thank you!
> Also the import statement doesnt give any advantages over the require statement as far as I can see, since its only used in a config file.
