### ISSUE TITLE
Disable Logging and rawscreenshots

### ISSUE THREAD

**Issue by SanthoshBonala** [presidenten/wdio-video-reporter#17]
Even after setting log level to silent in wdio config, video reporter still generates wdio-X-Y-Video-reporter.log and rawSeleniumVideoGrabs folder.
This is what loaded config for video reporter looks like

```JavaScript
Using config:{
  "debugMode": false,
  "logLevel": "info",
  "videoRenderTimeout": 5,
  "outputDir": "output",
  "allureOutputDir": "allure-results",
  "rawPath": "rawSeleniumVideoGrabs",
  "usingAllure": false,
  "saveAllVideos": true,
  "videoSlowdownMultiplier": 20,
  "excludedActions": [],
  "jsonWireActions": [
    "url",
    "forward",
    "back",
    "refresh",
    "execute",
    "size",
    "position",
    "maximize",
    "click",
    "submit",
    "value",
    "keys",
    "clear",
    "selected",
    "enabled",
    "displayed",
    "orientation",
    "alert_text",
    "accept_alert",
    "dismiss_alert",
    "moveto",
    "buttondown",
    "buttonup",
    "doubleclick",
    "down",
    "up",
    "move",
    "scroll",
    "doubleclick",
    "longclick",
    "flick",
    "location"
  ]
}
```

**Comment by presidenten** [comment]
Ok, Ill have a look tomorrow.

**Comment by presidenten** [comment]
This is now resolved in https://github.com/presidenten/wdio-video-reporter/commit/c8e9da68d7937d68619fabba2f87bc75e66165fb

The `rawSeleniumGrabs` is unfortunately part of the reporter and cant be removed safely from within the reporter without risking video corruption on slower machines. This is because I dont have a hook for when all runners are done, only when a single runner is done. So trying to remove the raw-directory could end in another runner not having the material to generate videos.

I will release 1.4.5 as soon as I have closed a few more of the issues that poped up during my vacation this summer.

**Comment by mohsenny** [comment]
Can we please have the possibility to pass a flag to skip the creation of `rawSeleniumVideoGrabs` and its content. The job is failing because of the path being too long for `mkdir`:

` name too long, mkdir '/home/circleci/project/ui-test/screenshots/rawSeleniumVideoGrabs/Unpublished-Job--Job-CAREER-PAGE-STATUS-is-unpublished-for-ats-compoany--Job-STATUS-is-unpublished_by_recruiter-and-CAREER-PAGE-STATUS-is-unpublished--should-redirect-to-search-page-with-same-city-and-job-type--CHROME--01-08-2020--13-23-54-458'`
