### ISSUE TITLE
Question: Why wdio-video-reporter add allure's arguments?

### ISSUE THREAD

**Issue by aha-oretama** [presidenten/wdio-video-reporter#22]
**Describe the bug**
See these lines.
I have a question. Why  wdio-video-reporter add allure's argument?
https://github.com/presidenten/wdio-video-reporter/blob/04f5a248d202c4a199e5cd5065516e79deb67993/src/index.js#L134-L141

When a test is retried and first time's test fails and next test  succeeds, this makes allure reporter display not one test case but two test cases.
( Because failed test doesn't pass above lines when an error is thrown in mocha's `beforeEach`, and succeeded test has above argument but failed test has no argument)

**Expected behavior**
I think that `wdio-video-reporter` has a responsibility to video, not to allure. So these lines are not required in `wdio-video-reporter`, right?

**Comment by presidenten** [comment]
They are only run if allure is configured in wdio.conf.js (example here: https://github.com/presidenten/wdio-video-reporter/blob/04f5a248d202c4a199e5cd5065516e79deb67993/demo/wdio.conf.js#L34)

The reason is described in the Appium setup section of the readme:
https://github.com/presidenten/wdio-video-reporter#appium-setup
Basically Allure reports breaks down when testing multiple browsers which has to be registered with the same name, but run on different devices, for example: desktop safari, iphone safari and ipad safari (if I remember correctly, or maybe it was android? we run tests on desktop chrome, safari, firefox, ie11, edge, real ipad, real iphone, real android phone and real android pad).

If there is a bug associated with this, would you mind forking https://github.com/presidenten/wdio-template and setting up a scenario where the bug is easily reproduced so I can have a look and try to solve it?

**Comment by aha-oretama** [comment]
Sorry, I couldn't reproduce easily.
When the following error occurs in `beforeEach` step, what I explained can be reproduced. However, the following error cannot be caused manullly...
```
Session [ad579784925526caa974855a88525e69] not available and is not among the last 1000 terminated sessions.
                Active sessions are[ext. key 586442c27348ddf8423c5272a80fdaa6, ext. key bfb6e0d4a02b23fdda0b18c0483a54d8, ext. key 8fc80b6158caf0d16b58c7086ebeeb89, ext. key 4aba73b3e530228bae1839a322bd7b62, ext. key 9c3edd1cebefda7f9220fbc68cdce21b]
```

So I close this issue....
