### ISSUE TITLE
How can I save video for every failed as well as passed test case?

### ISSUE THREAD

**Issue by Biswajeet11** [presidenten/wdio-video-reporter#3]
If I want to record for each test case what should be done to store all the .mp4 files for all passed as well as failed test cases.

**Comment by presidenten** [comment]
In the configuration object there is a parameter called `saveAllVideos`. Just set it to `true` like so:

```
 reporters: [
    [video, {
      saveAllVideos: true,        // If true, also saves videos for successful test cases
      videoSlowdownMultiplier: 3, // Higher to get slower videos, lower for faster videos [Value 1-100]
    }],
  ],
```

You can read more about the configuration options in the last three sections in the readme:
https://github.com/presidenten/wdio-video-reporter#add-the-reporter-to-config

Ps. 
If you are testing on devices, make sure to update to the latest 1.2.4 release, since it adds the value of a custom capability; `deviceType`, as a allure argument for all test cases and also adds it to the video filenames, which makes it easier to separate desktop chrome, android phone chrome and android pad chrome for example, as well as safari for mac, iphone and ipad.
Just remember to specify it as a capability when setting up the device in appium.

filenames will be:
```
User-interactions--should-be-able-to-multi-select-in-dropdown-fails-by-design-to-gen-video--SAFARI--04-25-2019--17-41-54-232.mp4

User-interactions--should-be-able-to-multi-select-in-dropdown-fails-by-design-to-gen-video--SAFARI-iPad--04-25-2019--17-42-01-401.mp4

User-interactions--should-be-able-to-multi-select-in-dropdown-fails-by-design-to-gen-video--SAFARI-iPhone--04-25-2019--17-41-55-952
```
