### ISSUE TITLE
Video will not be created if a failure/error occurs in a BEFORE hook

### ISSUE THREAD

**Issue by Faz540** [presidenten/wdio-video-reporter#33]
**Describe the bug**
If I'm using a Mocha framework and I have before hook that navigates to a page and waits for an element to exist, if the element does not exist - then a video will not be created.
If I move that one "wait for element to exist" command out of the before hook and into the "it" block, the video will be successfully created.

Apologies if this issue is basically a duplicate of the below!
https://github.com/presidenten/wdio-video-reporter/issues/11

**Log**
https://pastebin.com/YJkqKVM3

**To Reproduce**
I've created a repo with an example.
https://github.com/Faz540/wdio-video-reporter-bug

**Expected behaviour**
I'd expect a video to be created if the element cannot be found, regardless if that check is inside a before hook or the actual test itself.

**Environment (please complete the following information):**
 - **wdio-video-reporter version:** 2.0.0
 - **WebdriverIO version:** 5.18.6
 - **Mode:** [Standalone mode or WDIO Testrunner] WDIO Test Runner
 - **If WDIO Testrunner, running sync/async:** Sync
 - **Node.js version:** 13.2.0
 - **NPM version:** 6.13.6
 - **Browser name and version:** Chrome v79
 - **Platform name and version:** MacOS Mojave 10.14.6

**Additional context**
I'm using the Chromedriver service, not the Selenium Standalone.

**Comment by presidenten** [comment]
First of all, thanks for this excellent bug report!
Your example was easy to run and examine.

So to the issue at hand. 

It is correct that no video will be recorded if the exception happens in a before handler. The reason is that I do not have any test information at that point, so I dont know which name to put on the files. The test information comes in the "onTestStart"-hook. 
You can see the available hooks here:
https://webdriver.io/docs/customreporter.html#event-handler

Also, I didnt include all `jsonWireCommands` to be candidates for triggering screenshots as this makes tests reaaaally slow. Like really slow. So I chose to only take screenshots after "actions" where the users clicks or such, as it is described in the readme under pros and cons.

But, I did make an easy way to add more commands after which to take screenshots for the video. 
It is described in the readme under [Advanced configuration parameters](https://github.com/presidenten/wdio-video-reporter#advanced-configuration-parameters). Just add an array to the config that is called `addJsonWireActions` and fill it with which ever [jsonWireACommands](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#command-summary) where you might want screenshots.

The default `jsonWireCommands` are specified here: https://github.com/presidenten/wdio-video-reporter/blob/master/src/config.js#L33
