### ISSUE TITLE
Extend wdio-video-reporter to support WebdriverIO v6

### ISSUE THREAD

**Issue by und3fined-v01d** [presidenten/wdio-video-reporter#43]
**Is your feature request related to a problem? Please describe.**
The `wdio-video-reporter` npm package made video recording of test runs nearly seamless with WebdriverIO v5. Because of how useful recording of tests can prove to be, an extension to support WebdriverIO v6 should not be a bad consideration more so because of the fact that this is the only plugin that supports video recording for WebdriverIO v6.

**Describe the solution you'd like**
A start can be with upgrading `@wdio/reporter` npm package to the latest version.

**Comment by AlQaholic007** [comment]
I would love to work on this, if someone can approve this, I would love to create a PR.

**Comment by presidenten** [comment]
Thank you! 

I would actually appreciate it very much, since I have alot to do at work at the moment.

What needs to be done in main lib:
- packages updated with yarn
- test
- bulid

What needs to be done in demo dir:
- packages updated with yarn
- try jasmine style tests with `yarn e2e` and check report
- try cucumber style tests with `yarn e2e-cucumber` and check report

If possible, also try the built file with the template at: https://github.com/presidenten/wdio-template

**Comment by AlQaholic007** [comment]
Thank you so much for guiding me with the first steps. I'll try to work on it and raise a PR.

**Comment by presidenten** [comment]
No problem, feel free to ask questions if you get stuck.

**Comment by AlQaholic007** [comment]
Hey @presidenten , can you help me with a weird problem. So I have successfully upgraded the package to support v6

**Comment by AlQaholic007** [comment]
However I am facing a weird issue on one of the tests, the test for multiselect. It selects multiple options but on clicking the display all, it displays only one option. This is a bug with the https://seleniumeasy.com/test/ website since I tried that with my mac manually and still face the same issue

**Comment by AlQaholic007** [comment]
<img width="611" alt="Screenshot 2020-05-26 at 7 07 02 PM" src="https://user-images.githubusercontent.com/55358652/82907408-34e2ce00-9f84-11ea-83a1-5d51598c1e23.png">

**Comment by AlQaholic007** [comment]
All other tests pass

```
------------------------------------------------------------------
[chrome 83.0.4103.61 Mac OS X #0-0] Spec: /Users/soham/Desktop/wdio-video-reporter/demo/specs/selenium-easy.e2e.js
[chrome 83.0.4103.61 Mac OS X #0-0] Running: chrome (v83.0.4103.61) on Mac OS X
[chrome 83.0.4103.61 Mac OS X #0-0] Session ID: 80e3685fcb980a34f2108c2c8847b675
[chrome 83.0.4103.61 Mac OS X #0-0]
[chrome 83.0.4103.61 Mac OS X #0-0] User interactions
[chrome 83.0.4103.61 Mac OS X #0-0]    ✓ should be able to edit input (should pass)
[chrome 83.0.4103.61 Mac OS X #0-0]    ✓ should be able to move slider (fails by design to gen video)
[chrome 83.0.4103.61 Mac OS X #0-0]    ✖ should be able to multi-select in dropdown (fails by design to gen video)
[chrome 83.0.4103.61 Mac OS X #0-0]
[chrome 83.0.4103.61 Mac OS X #0-0] Reporter bug fixes (should pass)
[chrome 83.0.4103.61 Mac OS X #0-0]    ✓ should handle modals blocking screenshots
[chrome 83.0.4103.61 Mac OS X #0-0]
[chrome 83.0.4103.61 Mac OS X #0-0] 3 passing (36.1s)
[chrome 83.0.4103.61 Mac OS X #0-0] 1 failing
[chrome 83.0.4103.61 Mac OS X #0-0]
[chrome 83.0.4103.61 Mac OS X #0-0] 1) User interactions should be able to multi-select in dropdown (fails by design to gen video)
[chrome 83.0.4103.61 Mac OS X #0-0] Expected false to be true.
[chrome 83.0.4103.61 Mac OS X #0-0] Error: Expected false to be true.
[chrome 83.0.4103.61 Mac OS X #0-0]     at <Jasmine>
[chrome 83.0.4103.61 Mac OS X #0-0]     at UserContext.<anonymous> (/Users/soham/Desktop/wdio-video-reporter/demo/specs/selenium-easy.e2e.js:66:40)
[chrome 83.0.4103.61 Mac OS X #0-0] Expected false to be true.
[chrome 83.0.4103.61 Mac OS X #0-0] Error: Expected false to be true.
[chrome 83.0.4103.61 Mac OS X #0-0]     at <Jasmine>
[chrome 83.0.4103.61 Mac OS X #0-0]     at UserContext.<anonymous> (/Users/soham/Desktop/wdio-video-reporter/demo/specs/selenium-easy.e2e.js:67:37)
[chrome 83.0.4103.61 Mac OS X #0-0] Expected false to be true.
[chrome 83.0.4103.61 Mac OS X #0-0] error properties: Object({ matcherName: 'toBe', passed: false, expected: true, actual: false })
[chrome 83.0.4103.61 Mac OS X #0-0] Error: Expected false to be true.
[chrome 83.0.4103.61 Mac OS X #0-0]     at <Jasmine>
[chrome 83.0.4103.61 Mac OS X #0-0]     at UserContext.<anonymous> (/Users/soham/Desktop/wdio-video-reporter/demo/specs/selenium-easy.e2e.js:66:40)


Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:43 

error Command failed with exit code 1.
```

**Comment by AlQaholic007** [comment]
Do you think we could possibly replace this test with some other test?

**Comment by presidenten** [comment]
Not all the tests inte the demo-dir are supposed to pass. :-) Sorry I could not reply earlier. I see you have been working on this for some time. 

Anyways, note that some of them have `(fails by design to gen video)` in their name? Thats because I want to see a couple of failing tests and a couple of passing tests so I can verify that the `saveAllVideos` configuration option works. And also people can check a testrun and see what passing and failing tests looks like, since the default is that only failing tests generate videos.

The multiselect thingie is a bug on the website and the slider is wrong on purpose to give a failed test. Check the names :-) 

Only the unit tests for the main lib should pass, and coverage should be 100%.
Run only tests with `yarn test` or with coverage output with `yarn testcov`.

**Comment by AlQaholic007** [comment]
Ooppsss so silly of me to not have noticed the names🙈...the main unit tests all pass🥳...I guess it's PR time🤩
